package ge.kuku.movietable.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import ge.kuku.movietable.core.MovieDo;

@DynamoDBTable(tableName = "MovieTable")
public class MovieItem {
    private String id;
    private String imdbId;
    private String language;
    private String quality;
    private String source;
    private String name;

    public static MovieItem fromDo(MovieDo movieDo) {
        MovieItem movieItem = new MovieItem();
        movieItem.setImdbId(movieDo.getImdbId());
        movieItem.setLanguage(movieDo.getLanguage());
        movieItem.setQuality(movieDo.getQuality());
        movieItem.setSource(movieDo.getSource());
        movieItem.setName(movieDo.getName());
        return movieItem;
    }

    @DynamoDBRangeKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBHashKey(attributeName = "imdbId")
    public String getImdbId() {
        return imdbId;
    }

    public void setImdbId(String imdbId) {
        this.imdbId = imdbId;
    }

    @DynamoDBAttribute(attributeName = "Language")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @DynamoDBAttribute(attributeName = "Quality")
    public String getQuality() {
        return quality;
    }

    public void setQuality(String quality) {
        this.quality = quality;
    }

    @DynamoDBAttribute(attributeName = "Source")
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Movie [imdbId=" + imdbId + ", language=" + language
                + ", quality=" + quality + ", source=" + source + "]";
    }

    public MovieDo toDo() {
        MovieDo movieDo = new MovieDo();
        movieDo.setId(id);
        movieDo.setImdbId(imdbId);
        movieDo.setLanguage(language);
        movieDo.setQuality(quality);
        movieDo.setSource(source);
        movieDo.setName(name);
        return movieDo;
    }
}